import 'dart:typed_data';

part 'generated/vt_parser_table.g.dart';

/// Generated byte-level state transitions for the VT parser hot path.
///
/// A consumer first applies the byte's transition action. When the state
/// changes, or an explicit introducer starts the same state again, it then
/// applies the old state's exit action and the new state's entry action.
/// [VtParserTable.transitionStartsSequence] identifies ESC and C1 introducers
/// independently of intra-sequence state changes. Ordinary self-transitions
/// such as printable ground bytes do not run lifecycle actions. UTF-8
/// continuation bytes must remain with an already-pending decoder before
/// consulting this table, so a continuation that has the same value as an
/// 8-bit C1 control is not misclassified.
///
/// The generated integer accessors are intentionally allocation-free. Callers
/// on trusted hot paths may use the `Unchecked` forms with state IDs in
/// `0..<stateCount` and bytes in `0..<byteCount`.
