import 'dart:convert';

import 'terminal_config.dart';
import 'terminal_effective_config.dart';

enum TerminalConfigurationReferenceLimitKind { usage, markdown }

final class TerminalConfigurationReferenceLimitException implements Exception {
  const TerminalConfigurationReferenceLimitException({
    required this.kind,
    required this.actual,
    required this.maximum,
  });

  final TerminalConfigurationReferenceLimitKind kind;
  final int actual;
  final int maximum;

  @override
  String toString() =>
      'TerminalConfigurationReferenceLimitException(${kind.name}: '
      '$actual > $maximum)';
}

final class TerminalConfigurationReferenceLimits {
  const TerminalConfigurationReferenceLimits({
    this.maxUsageCharacters = 128 * 1024,
    this.maxMarkdownCharacters = 256 * 1024,
  });

  static const int maximumUsageCharacters = 1024 * 1024;
  static const int maximumMarkdownCharacters = 1024 * 1024;

  final int maxUsageCharacters;
  final int maxMarkdownCharacters;

  void validate() {
    _validate(maxUsageCharacters, maximumUsageCharacters, 'maxUsageCharacters');
    _validate(
      maxMarkdownCharacters,
      maximumMarkdownCharacters,
      'maxMarkdownCharacters',
    );
  }

  static void _validate(int value, int maximum, String name) {
    if (value < 1 || value > maximum) {
      throw ArgumentError.value(value, name, 'must be in 1..$maximum');
    }
  }
}

/// Generates user-visible CLI and Markdown from the typed product schema.
final class TerminalConfigurationReference {
  factory TerminalConfigurationReference({
    TerminalConfigSchema? schema,
    TerminalConfigurationReferenceLimits limits =
        const TerminalConfigurationReferenceLimits(),
  }) {
    limits.validate();
    return TerminalConfigurationReference._(
      schema ?? TerminalProductConfigSchema.instance,
      limits,
    );
  }

  const TerminalConfigurationReference._(this.schema, this.limits);

  final TerminalConfigSchema schema;
  final TerminalConfigurationReferenceLimits limits;

  String generateUsage() {
    final _ReferenceWriter writer = _ReferenceWriter(
      TerminalConfigurationReferenceLimitKind.usage,
      limits.maxUsageCharacters,
    );
    writer
      ..line('Usage: Dart Terminal [options]')
      ..line()
      ..line('Process modes:')
      ..line('  --help')
      ..line('      Print this schema-generated help and exit.')
      ..line('  --show-config')
      ..line('      Resolve and print the effective configuration, then exit.')
      ..line()
      ..line('Configuration selectors:')
      ..line('  --config=<path>')
      ..line('      Read an explicit configuration file.')
      ..line('  --no-config')
      ..line('      Do not read any configuration file.')
      ..line()
      ..line('Schema options:');
    for (final TerminalConfigOptionBase option in schema.options) {
      final String repetition = option.isRepeatable
          ? ' Repeatable up to ${option.maximumOccurrences} times.'
          : '';
      writer
        ..line('  --${option.name}=${option.valueSyntax}')
        ..line(
          '      ${option.description} Policy: '
          '${_policy(option.applicationPolicy)}.$repetition',
        );
    }
    writer
      ..line()
      ..line(
        'Detailed configuration and keybinding references are installed with '
        'the source documentation.',
      );
    return writer.finish();
  }

  String generateMarkdown() {
    final TerminalConfigLimits configLimits = const TerminalConfigLimits();
    final _ReferenceWriter writer = _ReferenceWriter(
      TerminalConfigurationReferenceLimitKind.markdown,
      limits.maxMarkdownCharacters,
    );
    writer
      ..line('# Configuration and command-line reference')
      ..line()
      ..line(
        '<!-- Generated by tool/generate_configuration_reference.dart. '
        'Do not edit by hand. -->',
      )
      ..line()
      ..line(
        'This reference is generated from Dart Terminal’s typed configuration '
        'schema. Option names, syntax, defaults, repeatability, and '
        'application policies must therefore match `--help`, `--show-config`, '
        'and the native Settings inspector.',
      )
      ..line()
      ..line('## Process modes')
      ..line()
      ..line('- `--help` prints schema-generated usage without reading config.')
      ..line(
        '- `--show-config` resolves configuration and prints the bounded '
        '`${TerminalEffectiveConfigFormatter.formatName}` version '
        '${TerminalEffectiveConfigFormatter.formatVersion} document without '
        'starting the terminal application.',
      )
      ..line(
        '- `--show-config` may be combined with `--config=PATH`, '
        '`--no-config`, and the schema options below. It cannot be combined '
        'with `--help` or integration-only runtime arguments.',
      )
      ..line()
      ..line('## Files, syntax, and precedence')
      ..line()
      ..line(
        'The default file is `\$XDG_CONFIG_HOME/dart-terminal/config`, or '
        '`~/Library/Application Support/Dart Terminal/config` when '
        '`XDG_CONFIG_HOME` is unset. A missing default file is ignored. Use '
        '`--config=PATH` for an explicit file or `--no-config` to skip files.',
      )
      ..line()
      ..line(
        'Files are UTF-8 `name = value` assignments. Blank lines and comments '
        'are accepted; quote values containing spaces or `#`. `include` paths '
        'are resolved relative to the including file. Precedence is schema '
        'default, included files, including file, then command line.',
      )
      ..line()
      ..line(
        'Resolution is bounded to ${configLimits.maxFiles} files, include depth '
        '${configLimits.maxIncludeDepth}, ${configLimits.maxFileBytes} bytes '
        'per file, ${configLimits.maxLineCharacters} UTF-16 units per line, '
        '${configLimits.maxAssignments} assignments, and '
        '${configLimits.maxDiagnostics} diagnostics.',
      )
      ..line()
      ..line('## Schema options')
      ..line()
      ..line(
        '| Option | Command line | Value syntax | Default | Policy | '
        'Repeatability | Description |',
      )
      ..line('| --- | --- | --- | --- | --- | --- | --- |');
    for (final TerminalConfigOptionBase option in schema.options) {
      writer.line(
        '| ${_code(option.name)} | ${_code('--${option.name}=VALUE')} | '
        '${_code(option.valueSyntax)} | ${_code(_defaultValue(option))} | '
        '${_policy(option.applicationPolicy)} | ${_repeatability(option)} | '
        '${_cell(option.description)} |',
      );
    }
    writer
      ..line()
      ..line('## Diagnostics and migration')
      ..line()
      ..line(
        'File diagnostics retain severity, stable code, path, line, column, '
        'and a repair hint when available. Error-bearing startup snapshots '
        'recover to the last valid value or schema default. Error-bearing '
        'reload candidates are rejected atomically; warning-only candidates '
        'are accepted.',
      )
      ..line()
      ..line(
        'The compatibility spelling `theme = default` resolves to `system` '
        'but emits `CFG_DEPRECATED_VALUE`; replace it with '
        '`theme = system`. Canonical effective output always reports `system`.',
      )
      ..line()
      ..line('## Keybindings and actions')
      ..line()
      ..line(
        'The repeatable `keybind` option uses `chord=target`. Physical key '
        'names, modifier ordering, pane/application action IDs, standard '
        'bindings, and reserved native shortcuts are generated separately in '
        '[Keybindings and actions](keybindings-and-actions.md).',
      );
    return writer.finish();
  }

  static String _defaultValue(TerminalConfigOptionBase option) {
    if (option.isRepeatable) return '<none>';
    return option.formatObject(option.defaultValueObject) ?? '<unset>';
  }

  static String _policy(TerminalConfigApplicationPolicy policy) =>
      switch (policy) {
        TerminalConfigApplicationPolicy.live => 'live',
        TerminalConfigApplicationPolicy.newSession => 'new-session',
      };

  static String _repeatability(TerminalConfigOptionBase option) =>
      option.isRepeatable
      ? 'ordered, max ${option.maximumOccurrences}'
      : 'once';

  static String _cell(String value) => value
      .replaceAll(r'\', r'\\')
      .replaceAll('|', r'\|')
      .replaceAll('\n', ' ');

  static String _code(String value) =>
      '<code>${const HtmlEscape(HtmlEscapeMode.element).convert(value)}</code>';
}

final class _ReferenceWriter {
  _ReferenceWriter(this.kind, this.maximumCharacters);

  final TerminalConfigurationReferenceLimitKind kind;
  final int maximumCharacters;
  final StringBuffer _buffer = StringBuffer();
  var _characters = 0;

  void line([String value = '']) {
    final int next = _characters + value.length + 1;
    if (next > maximumCharacters) {
      throw TerminalConfigurationReferenceLimitException(
        kind: kind,
        actual: next,
        maximum: maximumCharacters,
      );
    }
    _buffer
      ..write(value)
      ..write('\n');
    _characters = next;
  }

  String finish() => _buffer.toString();
}
