import 'dart:io';

import '../lib/src/terminal_action_registry.dart';
import '../lib/src/terminal_config.dart';
import '../lib/src/terminal_input/terminal_key_binding.dart';
import '../lib/src/terminal_input/terminal_key_event.dart';

const String keybindActionReferencePath =
    'docs/reference/keybindings-and-actions.md';

final class KeybindActionReferenceException implements Exception {
  const KeybindActionReferenceException(this.message);

  final String message;

  @override
  String toString() => 'KeybindActionReferenceException: $message';
}

String generateKeybindActionReference() {
  final _ReferenceInventory inventory = _ReferenceInventory.load();
  final TerminalConfigLimits configLimits = const TerminalConfigLimits();
  final StringBuffer output = StringBuffer()
    ..writeln('# Keybindings and actions')
    ..writeln()
    ..writeln(
      '<!-- Generated by tool/generate_keybind_action_reference.dart. '
      'Do not edit by hand. -->',
    )
    ..writeln()
    ..writeln(
      'This reference is generated from Dart Terminal’s typed physical-key, '
      'binding, and application-action authorities.',
    )
    ..writeln()
    ..writeln('## Declaration syntax')
    ..writeln()
    ..writeln('Use one declaration per binding:')
    ..writeln()
    ..writeln('```text')
    ..writeln('keybind = shift+control+k=pane.focus-next')
    ..writeln('```')
    ..writeln()
    ..writeln(
      'The left side is one physical key plus zero or more exact modifiers. '
      'Each modifier may appear once; the canonical order is '
      '${_codeList(TerminalKeyBindingVocabulary.modifierConfigNames)}. '
      'Names and action IDs are case-sensitive.',
    )
    ..writeln()
    ..writeln(
      'Bindings are applied in include, including file, then command-line '
      'order. A later declaration of the same exact chord replaces an '
      'earlier declaration. Up to '
      '${TerminalProductConfigSchema.keybind.maximumOccurrences} configured '
      'declarations are retained, in addition to '
      '${TerminalKeyBindingEngine.standardDefinitionCount} standard binding. '
      'One keybind value is limited to '
      '${TerminalKeyBindingLimits.maximumConfigurationUnits} UTF-16 units; '
      'the enclosing configuration also limits a line to '
      '${configLimits.maxLineCharacters} units and all assignments to '
      '${configLimits.maxAssignments}.',
    )
    ..writeln()
    ..writeln(
      'Invalid declarations are diagnosed independently and omitted. '
      'Application actions are dispatched without blocking key delivery. '
      'Busy, unavailable, or failed actions are consumed and never fall '
      'through as terminal bytes.',
    )
    ..writeln()
    ..writeln('Special targets:')
    ..writeln()
    ..writeln(
      '- `${TerminalKeyBindingDefinition.unbindConfigName}` removes any '
      'binding for the exact chord, restoring ordinary terminal encoding.',
    )
    ..writeln(
      '- `${TerminalKeyBindingDefinition.passthroughConfigName}` explicitly '
      'removes Command from the matched event and sends the remaining '
      'key event through the terminal encoder.',
    )
    ..writeln()
    ..writeln('The same option may be repeated on the command line:')
    ..writeln()
    ..writeln('```shell')
    ..writeln('make RUNTIME_ARCH=arm64 developer-jit-run \\')
    ..writeln(
      '  RUNTIME_ARGUMENTS="--keybind=control+d=unbind '
      '--keybind=control+k=pane.focus-next"',
    )
    ..writeln('```')
    ..writeln()
    ..writeln('## Standard bindings')
    ..writeln()
    ..writeln('| Chord | Target |')
    ..writeln('| --- | --- |');
  for (final TerminalKeyBindingDefinition binding
      in TerminalKeyBindingEngine.standardDefinitions) {
    output.writeln(
      '| `${binding.chord.configName}` | `${binding.targetConfigName}` |',
    );
  }
  output
    ..writeln()
    ..writeln('## Physical keys')
    ..writeln()
    ..writeln(
      'These are physical positions. Produced text, keyboard layout, Caps '
      'Lock, numeric-pad provenance, Function, and key repeat are not part '
      'of chord identity.',
    )
    ..writeln();
  _writeKeyGroup(output, 'Letters', inventory.letterKeys);
  _writeKeyGroup(output, 'Digits', inventory.digitKeys);
  _writeKeyGroup(output, 'Function keys', inventory.functionKeys);
  _writeKeyGroup(output, 'Keypad', inventory.keypadKeys);
  _writeKeyGroup(output, 'JIS', inventory.jisKeys);
  _writeKeyGroup(output, 'Other', inventory.otherKeys);
  output
    ..writeln()
    ..writeln('## Pane actions')
    ..writeln()
    ..writeln('| Target ID | Behavior |')
    ..writeln('| --- | --- |');
  for (final TerminalKeyBindingAction action
      in TerminalKeyBindingAction.values) {
    output.writeln(
      '| `${action.configName}` | ${_paneActionDescription(action)} |',
    );
  }
  output
    ..writeln()
    ..writeln('## Application actions')
    ..writeln()
    ..writeln(
      'Every ID below can be a target on a non-reserved chord. Availability '
      'is evaluated when the chord is invoked.',
    )
    ..writeln()
    ..writeln('| Target ID | Title | Menu | Native shortcut |')
    ..writeln('| --- | --- | --- | --- |');
  for (final TerminalActionDefinition action in inventory.catalog.actions) {
    final TerminalActionShortcut? shortcut = action.shortcut;
    final String shortcutText = shortcut == null
        ? '—'
        : '`${inventory.chordForShortcut(shortcut).configName}`';
    output.writeln(
      '| `${action.id.stableName}` | ${_cell(action.title)} | '
      '${action.menu.name} | $shortcutText |',
    );
  }
  output
    ..writeln()
    ..writeln('## Reserved native shortcuts')
    ..writeln()
    ..writeln(
      'AppKit consumes these standard menu shortcuts before raw terminal key '
      'routing. A `keybind` declaration using one is rejected with '
      '`CFG_INVALID_VALUE`; choose a different chord. This reservation '
      'applies to the chord, regardless of its configured target.',
    )
    ..writeln()
    ..writeln('| Chord | Native action | Title |')
    ..writeln('| --- | --- | --- |');
  for (final TerminalActionDefinition action
      in inventory.reservedNativeActions) {
    output.writeln(
      '| `${inventory.chordForShortcut(action.shortcut!).configName}` | '
      '`${action.id.stableName}` | ${_cell(action.title)} |',
    );
  }
  return output.toString();
}

bool keybindActionReferenceIsFresh(File output) =>
    output.existsSync() &&
    output.readAsStringSync() == generateKeybindActionReference();

void validateKeybindActionReferenceSource(
  String source, {
  String? expectedSource,
}) {
  final String expected = expectedSource ?? generateKeybindActionReference();
  if (source != expected) {
    throw const KeybindActionReferenceException(
      'keybinding/action reference is stale',
    );
  }
}

String keybindActionReferencePassLine() {
  final _ReferenceInventory inventory = _ReferenceInventory.load();
  return 'KEYBIND_ACTION_REFERENCE_CHECK_PASS '
      'keys=${inventory.keys.length} '
      'pane_actions=${TerminalKeyBindingAction.values.length} '
      'application_actions=${inventory.catalog.actions.length} '
      'standard_bindings=${TerminalKeyBindingEngine.standardDefinitions.length} '
      'reserved_shortcuts=${inventory.reservedNativeActions.length}';
}

final class _ReferenceInventory {
  _ReferenceInventory._({
    required this.catalog,
    required this.keys,
    required this.namesByKey,
    required this.reservedNativeActions,
    required this.chordsByShortcut,
  });

  factory _ReferenceInventory.load() {
    final TerminalActionCatalog catalog = TerminalActionCatalog.standard();
    final List<TerminalPhysicalKey> keys = TerminalPhysicalKey.values
        .where((TerminalPhysicalKey key) => key != TerminalPhysicalKey.unknown)
        .toList(growable: false);
    final Map<TerminalPhysicalKey, String> namesByKey =
        <TerminalPhysicalKey, String>{
          for (final TerminalPhysicalKey key in keys)
            key: TerminalKeyBindingVocabulary.configNameForKey(key),
        };
    _requireUnique(namesByKey.values, 'physical key config names');
    for (final MapEntry<TerminalPhysicalKey, String> entry
        in namesByKey.entries) {
      if (entry.value.isEmpty ||
          TerminalKeyBindingVocabulary.keyFromConfigName(entry.value) !=
              entry.key) {
        throw KeybindActionReferenceException(
          'physical key `${entry.key.name}` does not round-trip',
        );
      }
    }
    _requireUnique(
      TerminalKeyBindingVocabulary.modifierConfigNames,
      'modifier config names',
    );
    final List<String> targetNames = <String>[
      ...TerminalKeyBindingAction.values.map(
        (TerminalKeyBindingAction action) => action.configName,
      ),
      ...TerminalActionId.values.map(
        (TerminalActionId action) => action.stableName,
      ),
      TerminalKeyBindingDefinition.unbindConfigName,
      TerminalKeyBindingDefinition.passthroughConfigName,
    ];
    _requireUnique(targetNames, 'keybind target names');
    if (catalog.actions.length != TerminalActionId.values.length ||
        TerminalActionId.values.any(
          (TerminalActionId id) => catalog.actionForId(id) == null,
        )) {
      throw const KeybindActionReferenceException(
        'the standard catalog must cover every application action',
      );
    }
    if (TerminalKeyBindingEngine.standardDefinitionCount !=
        TerminalKeyBindingEngine.standardDefinitions.length) {
      throw const KeybindActionReferenceException(
        'standard binding count does not match its definitions',
      );
    }
    if (TerminalProductConfigSchema.keybind.maximumOccurrences +
            TerminalKeyBindingEngine.standardDefinitionCount !=
        TerminalKeyBindingEngine.maximumDefinitionCount) {
      throw const KeybindActionReferenceException(
        'configured and standard binding bounds do not reconcile',
      );
    }
    final List<TerminalActionDefinition> reservedNativeActions = catalog.actions
        .where((TerminalActionDefinition action) => action.shortcut != null)
        .toList(growable: false);
    final Map<TerminalActionShortcut, TerminalKeyBindingChord>
    chordsByShortcut = <TerminalActionShortcut, TerminalKeyBindingChord>{};
    final Set<TerminalKeyBindingChord> reservedChords =
        <TerminalKeyBindingChord>{};
    for (final TerminalActionDefinition action in reservedNativeActions) {
      final TerminalActionShortcut shortcut = action.shortcut!;
      final TerminalKeyBindingChord? chord =
          TerminalKeyBindingVocabulary.chordForNativeShortcut(shortcut);
      if (chord == null) {
        throw KeybindActionReferenceException(
          'native shortcut `${shortcut.identity}` has no physical key',
        );
      }
      if (!reservedChords.add(chord)) {
        throw KeybindActionReferenceException(
          'native shortcut chord `${chord.configName}` is duplicated',
        );
      }
      chordsByShortcut[shortcut] = chord;
    }
    for (final TerminalKeyBindingDefinition binding
        in TerminalKeyBindingEngine.standardDefinitions) {
      if (binding.chord.physicalKey == TerminalPhysicalKey.unknown ||
          reservedChords.contains(binding.chord) ||
          !targetNames.contains(binding.targetConfigName)) {
        throw KeybindActionReferenceException(
          'standard binding `${binding.chord.configName}` is invalid',
        );
      }
    }
    return _ReferenceInventory._(
      catalog: catalog,
      keys: List<TerminalPhysicalKey>.unmodifiable(keys),
      namesByKey: Map<TerminalPhysicalKey, String>.unmodifiable(namesByKey),
      reservedNativeActions: List<TerminalActionDefinition>.unmodifiable(
        reservedNativeActions,
      ),
      chordsByShortcut:
          Map<TerminalActionShortcut, TerminalKeyBindingChord>.unmodifiable(
            chordsByShortcut,
          ),
    );
  }

  final TerminalActionCatalog catalog;
  final List<TerminalPhysicalKey> keys;
  final Map<TerminalPhysicalKey, String> namesByKey;
  final List<TerminalActionDefinition> reservedNativeActions;
  final Map<TerminalActionShortcut, TerminalKeyBindingChord> chordsByShortcut;

  List<String> get letterKeys => _namesWhere(
    (TerminalPhysicalKey key) => RegExp(r'^key[A-Z]$').hasMatch(key.name),
  );

  List<String> get digitKeys =>
      _namesWhere((TerminalPhysicalKey key) => key.name.startsWith('digit'));

  List<String> get functionKeys => _namesWhere(
    (TerminalPhysicalKey key) => RegExp(r'^f[0-9]+$').hasMatch(key.name),
  );

  List<String> get keypadKeys =>
      _namesWhere((TerminalPhysicalKey key) => key.name.startsWith('keypad'));

  List<String> get jisKeys =>
      _namesWhere((TerminalPhysicalKey key) => key.name.startsWith('jis'));

  List<String> get otherKeys => _namesWhere(
    (TerminalPhysicalKey key) =>
        !RegExp(r'^key[A-Z]$').hasMatch(key.name) &&
        !key.name.startsWith('digit') &&
        !RegExp(r'^f[0-9]+$').hasMatch(key.name) &&
        !key.name.startsWith('keypad') &&
        !key.name.startsWith('jis'),
  );

  TerminalKeyBindingChord chordForShortcut(TerminalActionShortcut shortcut) =>
      chordsByShortcut[shortcut]!;

  List<String> _namesWhere(bool Function(TerminalPhysicalKey key) predicate) =>
      List<String>.unmodifiable(
        keys
            .where(predicate)
            .map((TerminalPhysicalKey key) => namesByKey[key]!),
      );
}

void _requireUnique(Iterable<String> values, String description) {
  final Set<String> observed = <String>{};
  for (final String value in values) {
    if (!observed.add(value)) {
      throw KeybindActionReferenceException(
        '$description contains duplicate `$value`',
      );
    }
  }
}

void _writeKeyGroup(StringBuffer output, String label, List<String> names) {
  output.writeln('- $label: ${_codeList(names)}');
}

String _codeList(Iterable<String> values) =>
    values.map((String value) => '`$value`').join(', ');

String _paneActionDescription(TerminalKeyBindingAction action) =>
    switch (action) {
      TerminalKeyBindingAction.sendEndOfFile =>
        'Send the terminal end-of-file input action.',
      TerminalKeyBindingAction.sendInterruptSignal =>
        'Request the foreground process interrupt action.',
      TerminalKeyBindingAction.sendSuspendSignal =>
        'Request the foreground process suspend action.',
      TerminalKeyBindingAction.sendQuitSignal =>
        'Request the foreground process quit action.',
    };

String _cell(String value) =>
    value.replaceAll('|', r'\|').replaceAll('\n', ' ');

void main(List<String> arguments) {
  if (arguments.length != 1 ||
      (arguments.single != '--generate' && arguments.single != '--check')) {
    stderr.writeln(
      'KEYBIND_ACTION_REFERENCE_FAIL usage: '
      'dart run tool/generate_keybind_action_reference.dart '
      '--generate|--check',
    );
    exitCode = 64;
    return;
  }
  final Directory repositoryRoot = File.fromUri(Platform.script)
      .absolute
      .parent
      .parent;
  final File output = File.fromUri(
    repositoryRoot.uri.resolve(keybindActionReferencePath),
  );
  try {
    if (arguments.single == '--generate') {
      output.parent.createSync(recursive: true);
      output.writeAsStringSync(generateKeybindActionReference(), flush: true);
      stdout.writeln(
        'KEYBIND_ACTION_REFERENCE_GENERATED path=$keybindActionReferencePath',
      );
      return;
    }
    if (!keybindActionReferenceIsFresh(output)) {
      stderr.writeln(
        'KEYBIND_ACTION_REFERENCE_STALE path=$keybindActionReferencePath; '
        'regenerate with `make keybind-action-reference`',
      );
      exitCode = 1;
      return;
    }
    stdout.writeln(keybindActionReferencePassLine());
  } on Object catch (error) {
    stderr.writeln(error);
    exitCode = 1;
  }
}
